DROP TABLESPACE Esquema INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TempEsquema INCLUDING CONTENTS AND DATAFILES;
DROP TABLE PERSONAL CASCADE CONSTRAINTS;
DROP TABLE ALUMNO CASCADE CONSTRAINTS;
DROP TABLE PROFESOR CASCADE CONSTRAINTS;
DROP TABLE PERSONA CASCADE CONSTRAINTS;

DROP VIEW VISTA_MIEMBROS_UNIV;

DROP TABLESPACE Esquema INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TempEsquema INCLUDING CONTENTS AND DATAFILES;

CREATE SMALLFILE TABLESPACE Esquema
DATAFILE 
    'Esquema_01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 5G,
    'Esquema_02.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 5G
    LOGGING
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;
    
    CREATE TEMPORARY TABLESPACE TempEsquema
TEMPFILE 'TempEsquema_01.dbf' SIZE 100M 
    EXTENT MANAGEMENT LOCAL;

CREATE TABLE PERSONA (
    ID_PERSONA    NUMBER(10)      NOT NULL,
    NOMBRE        VARCHAR2(100)   NOT NULL,
    DIRECCION     VARCHAR2(200),
    TELEFONO      VARCHAR2(15),
    EMAIL         VARCHAR2(100)   UNIQUE,
    TIPO_PERSONA  VARCHAR2(10)    NOT NULL  
)
TABLESPACE Esquema;

CREATE TABLE PROFESOR (
    ID_PERSONA      NUMBER(10)      NOT NULL,
    DEPARTAMENTO    VARCHAR2(50),
    DEDICACION      VARCHAR2(50),
    CENTROS         VARCHAR2(200)  
)
TABLESPACE Esquema;

CREATE TABLE ALUMNO (
    ID_PERSONA      NUMBER(10)      NOT NULL,
    NUM_EXPEDIENTE  VARCHAR2(20)    UNIQUE NOT NULL, 
    TITULACION      VARCHAR2(100), 
    CENTRO_MATRICULA VARCHAR2(100) 
)
TABLESPACE Esquema;

CREATE TABLE PERSONAL (
    ID_PERSONA      NUMBER(10)      NOT NULL,
    UNIDAD_ADM      VARCHAR2(100),  
    CATEGORIA_PROF  VARCHAR2(50)    
)
TABLESPACE Esquema;

ALTER TABLE PERSONA
ADD CONSTRAINT PK_PERSONA PRIMARY KEY (ID_PERSONA)
USING INDEX TABLESPACE Esquema;

ALTER TABLE PERSONA
ADD CONSTRAINT CK_PERSONA_TIPO CHECK (TIPO_PERSONA IN ('PROFESOR', 'ALUMNO', 'PERSONAL'));

ALTER TABLE PROFESOR
ADD CONSTRAINT PK_PROFESOR PRIMARY KEY (ID_PERSONA)
USING INDEX TABLESPACE Esquema;

ALTER TABLE PROFESOR
ADD CONSTRAINT FK_PROFESOR_PERSONA FOREIGN KEY (ID_PERSONA)
REFERENCES PERSONA(ID_PERSONA);

ALTER TABLE ALUMNO
ADD CONSTRAINT PK_ALUMNO PRIMARY KEY (ID_PERSONA)
USING INDEX TABLESPACE Esquema;

ALTER TABLE ALUMNO
ADD CONSTRAINT FK_ALUMNO_PERSONA FOREIGN KEY (ID_PERSONA)
REFERENCES PERSONA(ID_PERSONA);

ALTER TABLE PERSONAL
ADD CONSTRAINT PK_PERSONAL PRIMARY KEY (ID_PERSONA)
USING INDEX TABLESPACE Esquema;

ALTER TABLE PERSONAL
ADD CONSTRAINT FK_PERSONAL_PERSONA FOREIGN KEY (ID_PERSONA)
REFERENCES PERSONA(ID_PERSONA);

CREATE OR REPLACE VIEW VISTA_MIEMBROS_UNIV AS
SELECT
    p.NOMBRE,
    p.DIRECCION,
    p.TELEFONO,
    p.EMAIL,
    p.TIPO_PERSONA,
    pr.DEPARTAMENTO AS Detalle_1,   
    pr.DEDICACION AS Detalle_2,     
    pr.CENTROS AS Detalle_3
FROM
    PERSONA p
JOIN
    PROFESOR pr ON p.ID_PERSONA = pr.ID_PERSONA
WHERE p.TIPO_PERSONA = 'PROFESOR'

UNION ALL

SELECT
    p.NOMBRE,
    p.DIRECCION,
    p.TELEFONO,
    p.EMAIL,
    p.TIPO_PERSONA,
    a.NUM_EXPEDIENTE AS Detalle_1,  
    a.TITULACION AS Detalle_2,      
    a.CENTRO_MATRICULA AS Detalle_3
FROM
    PERSONA p
JOIN
    ALUMNO a ON p.ID_PERSONA = a.ID_PERSONA
WHERE p.TIPO_PERSONA = 'ALUMNO'

UNION ALL

SELECT
    p.NOMBRE,
    p.DIRECCION,
    p.TELEFONO,
    p.EMAIL,
    p.TIPO_PERSONA,
    pe.UNIDAD_ADM AS Detalle_1,     
    pe.CATEGORIA_PROF AS Detalle_2, 
    NULL AS Detalle_3                
FROM
    PERSONA p
JOIN
    PERSONAL pe ON p.ID_PERSONA = pe.ID_PERSONA
WHERE p.TIPO_PERSONA = 'PERSONAL'

ORDER BY 1;

SET AUTOCOMMIT ON;

INSERT INTO PERSONA (ID_PERSONA, NOMBRE, DIRECCION, TELEFONO, EMAIL, TIPO_PERSONA)
VALUES (1, 'Ana Torres', 'Av. Universitaria 100', '987654321', 'ana.t@unmsm.pe', 'PROFESOR');

INSERT INTO PROFESOR (ID_PERSONA, DEPARTAMENTO, DEDICACION, CENTROS)
VALUES (1, 'Ingeniería de Sistemas', 'Tiempo Completo', 'FISI, FIEE');

INSERT INTO PERSONA (ID_PERSONA, NOMBRE, DIRECCION, TELEFONO, EMAIL, TIPO_PERSONA)
VALUES (2, 'Betty Rojas', 'Calle Los Sauces 500', '998877665', 'betty.r@unmsm.edu.pe', 'ALUMNO');

INSERT INTO ALUMNO (ID_PERSONA, NUM_EXPEDIENTE, TITULACION, CENTRO_MATRICULA)
VALUES (2, '2024001', 'Ingeniería de Software', 'Facultad de Ingeniería de Sistemas');

INSERT INTO PERSONA (ID_PERSONA, NOMBRE, DIRECCION, TELEFONO, EMAIL, TIPO_PERSONA)
VALUES (3, 'Carlos Soto', 'Jr. Las Palmeras 123', '976543210', 'carlos.s@unmsm.pe', 'PERSONAL');

INSERT INTO PERSONAL (ID_PERSONA, UNIDAD_ADM, CATEGORIA_PROF)
VALUES (3, 'Recursos Humanos', 'Administrativo Nivel 3');

COMMIT; 

CREATE INDEX IDX_PERSONA_NOMBRE
ON PERSONA (NOMBRE ASC)
TABLESPACE Esquema;

SELECT * FROM VISTA_MIEMBROS_UNIV;